# Generated by Django 5.0.4 on 2024-05-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Employee ID')),
                ('employee_name', models.CharField(max_length=200, verbose_name='Employee Name')),
                ('employee_department', models.CharField(max_length=30, verbose_name='Employee Department')),
                ('employee_dob', models.DateField(verbose_name='Employee Date of Birth')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loction_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shift Date', models.DateField()),
                ('Shift start', models.TimeField()),
                ('Shift End', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.employee')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.location')),
            ],
        ),
    ]
