# Generated by Django 5.0.4 on 2024-05-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='loction_name',
            new_name='location_name',
        ),
    ]
