# Generated by Django 5.0.4 on 2024-05-18 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_rename_loction_name_location_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeshift',
            name='Shift Date',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='Shift End',
        ),
        migrations.RemoveField(
            model_name='employeeshift',
            name='Shift start',
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 18), verbose_name='Shift Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='from_time',
            field=models.TimeField(default=datetime.time(19, 15, 46, 953279), verbose_name='Shift start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='to_time',
            field=models.TimeField(default=datetime.time(19, 15, 49, 916822), verbose_name='Shift End'),
            preserve_default=False,
        ),
    ]
